stages:
  make_apple:
    cmd: python gen_xy.py
    deps:
      - gen_xy.py
      - ui/__init__.py
    outs:
      - apple_position.in
  train:
    cmd: mkdir -p metrics/train && python train.py
    deps:
      - apple_position.in
      - train.py
      - brains/dqn.py
      - brains/dqn_cnn.py
      - neural_net/pytorch_cnn.py
    params:
      - train
    outs:
      - last_brain.pth
    plots:
      - metrics/train/loss.csv:
          cache: false
          y: loss
          y_label: loss
          x: episode
          x_label: episode
          title: Loss
      - metrics/train/rewards.csv:
          cache: false
          y: rewards
          y_label: rewards
          x: episode
          x_label: episode
          title: Rewards
