stages:
  train:
    cmd: python train.py
    deps:
      - apple_position.in
      - train.py
      - brains/dqn.py
      - brains/dqn_ann.py
      - neural_net/pytorch_ann.py
    params:
      - train
    outs:
      - last_brain.pth
    plots:
      - metrics/train/loss.csv:
          cache: false
          y: loss
          y_label: loss
          x: epochs
          x_label: epochs
          title: Loss
      - metrics/train/rewards.csv:
          cache: false
          y: rewards
          y_label: rewards
          x: epochs
          x_label: epochs
          title: Rewards
