stages:
  train:
    foreach:
      - algorithm: dqn
        network: ann
      - algorithm: dqn
        network: cnn
    do:
      cmd: mkdir -p metrics/train/${item.algorithm}_${item.network} && python train.py -a ${item.algorithm} -n ${item.network}
      deps:
        - train.py
        - brains/dqn.py
        - brains/${item.algorithm}_${item.network}.py
        - neural_net/pytorch_${item.network}.py
      params:
        - ${item.algorithm}_${item.network}
      outs:
        - output/${item.algorithm}_${item.network}/last_brain.pth
      plots:
        - metrics/train/${item.algorithm}_${item.network}/loss.csv:
            cache: false
            y: loss
            y_label: loss
            x: episode
            x_label: episode
            title: Loss
        - metrics/train/${item.algorithm}_${item.network}/rewards.csv:
            cache: false
            y: rewards
            y_label: rewards
            x: episode
            x_label: episode
            title: Rewards
        - metrics/train/${item.algorithm}_${item.network}/cum_rewards.csv:
            cache: false
            y: cum_rewards
            y_label: cumulative rewards
            x: episode
            x_label: episode
            title: Cumulative Rewards
