stages:
  train:
    foreach:
      - algorithm: dqn
        network: ann
      - algorithm: dqn
        network: cnn
    do:
      cmd: python train.py -a ${item.algorithm} -n ${item.network}
      deps:
        - train.py
        - brains/dqn.py
        - brains/${item.algorithm}_${item.network}.py
        - neural_net/pytorch_${item.network}.py
      params:
        - ${item.algorithm}_${item.network}.train
      outs:
        - output/${item.algorithm}_${item.network}/last_brain.pth
      live:
        metrics/train/${item.algorithm}_${item.network}:
          summary: true
          html: true
  test:
    foreach:
      - algorithm: dqn
        network: ann
      - algorithm: dqn
        network: cnn
    do:
      cmd: mkdir -p metrics/test/${item.algorithm}_${item.network} && python test.py -a ${item.algorithm} -n ${item.network}
      deps:
        - test.py
        - output/${item.algorithm}_${item.network}/last_brain.pth
      params:
        - ${item.algorithm}_${item.network}.test
      live:
        metrics/test/${item.algorithm}_${item.network}:
          summary: true
          html: true
