stages:
  make_apple:
    cmd: python gen_xy.py
    deps:
      - gen_xy.py
      - ui/__init__.py
    outs:
      - apple_position.in
  train:
    cmd: python train.py
    deps:
      - apple_position.in
      - train.py
      - brains/dqn.py
      - brains/dqn_cnn.py
      - neural_net/pytorch_cnn.py
    params:
      - train
    outs:
      - last_brain.pth
    plots:
      - loss.csv:
          cache: false
      - rewards.csv:
          cache: false
